K8s deamonset and chronjob

diff --git a/.github/workflows/member.yml b/.github/workflows/member.yml
--- a/.github/workflows/member.yml
+++ b/.github/workflows/member.yml
@@ -23,26 +23,26 @@ jobs:
       run: |
         echo "Checking if $AUTHOR is a member of team $TEAM in org $ORG"
 
-        TEAM_SLUG=$(echo "$TEAM" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
+        # TEAM_SLUG=$(echo "$TEAM" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
 
-        curl -H "Authorization: Bearer $GITHUB_TOKEN" \
-        -H "Accept: application/vnd.github+json" \
-        https://api.github.com/orgs/$ORG/teams
-
-
+        # curl -H "Authorization: Bearer $GITHUB_TOKEN" \
+        # -H "Accept: application/vnd.github+json" \
+        # https://api.github.com/orgs/$ORG/teams
 
 
 
-        # RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
-        #   -H "Authorization: Bearer $GITHUB_TOKEN" \
-        #   -H "Accept: application/vnd.github.v3+json" \
-        #   https://api.github.com/orgs/$ORG/teams/$TEAM_SLUG/memberships/$AUTHOR)
 
-        # if [ "$RESPONSE" != "204" ]; then
-        #   echo "::error::User $AUTHOR is not a member of $ORG"
-        #   exit 1
-        # else
-        #   echo "✅ $AUTHOR is a verified member of $ORG"
-        # fi
+
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
+          -H "Authorization: Bearer $GITHUB_TOKEN" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/orgs/$ORG/teams/12828425/memberships/$AUTHOR)
+
+        if [ "$RESPONSE" != "204" ]; then
+          echo "::error::User $AUTHOR is not a member of $ORG"
+          exit 1
+        else
+          echo "✅ $AUTHOR is a verified member of $ORG"
+        fi
 
 
